### ISSUE TITLE
Getting SSL error when submitting new file

### ISSUE THREAD

**Issue by pierreyves-lebrun** [shrinerb/shrine-tus-demo#6]
I recently got interested about Tus + Falcon projects and stumbled upon your work, which looks promising but I am getting a `Down::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed (self signed certificate)` error when clicking the submit button.

Below is what I get in the console:

```
user$ bundle exec falcon serve
 0.44s: #<Falcon::Endpoint https://localhost:9292/>
      : Falcon taking flight! Using Async::Container::Forked with concurrency: 8
 0.44s: Full status: kill -USR1 -61523
 0.45s: Per-process status: kill -USR1 61791
 0.45s: Per-process status: kill -USR1 61790
 0.45s: Per-process status: kill -USR1 61792
 0.45s: Per-process status: kill -USR1 61793
 0.45s: Per-process status: kill -USR1 61794
 0.45s: Per-process status: kill -USR1 61795
 0.45s: Per-process status: kill -USR1 61796
 0.45s: Per-process status: kill -USR1 61797
 1.29s: <Async::Task:0x3fd35ad54720 failed>
      |  OpenSSL::SSL::SSLError: SSL_accept SYSCALL returned=5 errno=0 state=unknown state
      |  → /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/async-io-1.18.2/lib/async/io/generic.rb:141 in `accept_nonblock'
      |    /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/async-io-1.18.2/lib/async/io/generic.rb:141 in `async_send'
      |    /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/async-io-1.18.2/lib/async/io/generic.rb:47 in `block in wrap_blocking_method'
      |    /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/async-io-1.18.2/lib/async/io/ssl_socket.rb:129 in `block in accept'
      |    /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/async-1.15.1/lib/async/task.rb:199 in `block in make_fiber'
::1 - - [26/Jan/2019:20:36:02 +0900] "GET /movies " 200 998 0.0168
::1 - - [26/Jan/2019:20:36:02 +0900] "GET /assets/css/app.css " 200 74 0.0020
::1 - - [26/Jan/2019:20:36:02 +0900] "GET /assets/js/app.js " 200 1167 0.0013
::1 - - [26/Jan/2019:20:36:02 +0900] "GET /assets/css/app.css " 200 74 0.0012
::1 - - [26/Jan/2019:20:36:02 +0900] "GET /assets/js/app.js " 200 1167 0.0009
::1 - - [26/Jan/2019:20:36:03 +0900] "GET /movies/new " 200 1770 0.0047
::1 - - [26/Jan/2019:20:36:03 +0900] "GET /assets/css/app.css " 200 74 0.0009
::1 - - [26/Jan/2019:20:36:03 +0900] "GET /assets/js/app.js " 200 1167 0.0009
::1 - - [26/Jan/2019:20:36:03 +0900] "GET /assets/css/app.css " 200 74 0.0010
::1 - - [26/Jan/2019:20:36:03 +0900] "GET /assets/js/app.js " 200 1167 0.0010
13.83s: Down::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed (self signed certificate)
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/down-4.8.0/lib/down/http.rb:135:in `request_error!'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/down-4.8.0/lib/down/http.rb:100:in `rescue in send_request'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/down-4.8.0/lib/down/http.rb:91:in `send_request'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/down-4.8.0/lib/down/http.rb:86:in `request'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/down-4.8.0/lib/down/http.rb:72:in `open'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/down-4.8.0/lib/down/backend.rb:17:in `open'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/shrine-url-2.2.1/lib/shrine/storage/url.rb:23:in `open'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/shrine-tus-1.2.2/lib/shrine/storage/tus.rb:28:in `open'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/shrine-2.14.0/lib/shrine/uploaded_file.rb:96:in `open'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/shrine-2.14.0/lib/shrine/uploaded_file.rb:254:in `io'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/shrine-2.14.0/lib/shrine/uploaded_file.rb:156:in `read'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/shrine-2.14.0/lib/shrine/storage/file_system.rb:131:in `copy_stream'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/shrine-2.14.0/lib/shrine/storage/file_system.rb:131:in `upload'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/shrine-2.14.0/lib/shrine.rb:303:in `copy'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/shrine-2.14.0/lib/shrine.rb:292:in `put'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/shrine-2.14.0/lib/shrine.rb:276:in `_store'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/shrine-2.14.0/lib/shrine.rb:203:in `store'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/shrine-2.14.0/lib/shrine/plugins/hooks.rb:97:in `block in store'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/shrine-2.14.0/lib/shrine/plugins/hooks.rb:103:in `around_store'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/shrine-2.14.0/lib/shrine/plugins/hooks.rb:97:in `store'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/shrine-2.14.0/lib/shrine/plugins/logging.rb:91:in `block in store'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/shrine-2.14.0/lib/shrine/plugins/logging.rb:106:in `block in log'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/shrine-2.14.0/lib/shrine/plugins/logging.rb:167:in `benchmark'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/shrine-2.14.0/lib/shrine/plugins/logging.rb:106:in `log'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/shrine-2.14.0/lib/shrine/plugins/logging.rb:91:in `store'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/shrine-2.14.0/lib/shrine.rb:181:in `upload'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/shrine-2.14.0/lib/shrine/plugins/hooks.rb:58:in `block in upload'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/shrine-2.14.0/lib/shrine/plugins/hooks.rb:64:in `around_upload'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/shrine-2.14.0/lib/shrine/plugins/hooks.rb:58:in `upload'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/shrine-2.14.0/lib/shrine/attacher.rb:191:in `store!'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/shrine-2.14.0/lib/shrine/attacher.rb:123:in `promote'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/shrine-2.14.0/lib/shrine/attacher.rb:117:in `_promote'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/shrine-2.14.0/lib/shrine/attacher.rb:112:in `finalize'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/shrine-2.14.0/lib/shrine/plugins/sequel.rb:94:in `block (2 levels) in included'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sequel-5.16.0/lib/sequel/database/transactions.rb:423:in `each'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sequel-5.16.0/lib/sequel/database/transactions.rb:423:in `remove_transaction'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sequel-5.16.0/lib/sequel/database/transactions.rb:269:in `_transaction'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sequel-5.16.0/lib/sequel/database/transactions.rb:220:in `block in transaction'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sequel-5.16.0/lib/sequel/connection_pool/threaded.rb:92:in `hold'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sequel-5.16.0/lib/sequel/database/connecting.rb:270:in `synchronize'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sequel-5.16.0/lib/sequel/database/transactions.rb:186:in `transaction'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sequel-5.16.0/lib/sequel/model/base.rb:1905:in `checked_transaction'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sequel-5.16.0/lib/sequel/model/base.rb:1465:in `block in save'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sequel-5.16.0/lib/sequel/model/base.rb:1893:in `checked_save_failure'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sequel-5.16.0/lib/sequel/model/base.rb:1465:in `save'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sequel-5.16.0/lib/sequel/model/base.rb:254:in `create'
  /Users/user/Documents/shrine-tus-demo/app.rb:50:in `block (3 levels) in <class:ShrineTusDemo>'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/roda-3.16.0/lib/roda.rb:854:in `if_match'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/roda-3.16.0/lib/roda.rb:783:in `_verb'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/roda-3.16.0/lib/roda.rb:554:in `post'
  /Users/user/Documents/shrine-tus-demo/app.rb:49:in `block (2 levels) in <class:ShrineTusDemo>'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/roda-3.16.0/lib/roda.rb:854:in `if_match'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/roda-3.16.0/lib/roda.rb:520:in `on'
  /Users/user/Documents/shrine-tus-demo/app.rb:38:in `block in <class:ShrineTusDemo>'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/roda-3.16.0/lib/roda.rb:282:in `instance_exec'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/roda-3.16.0/lib/roda.rb:282:in `block in call'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/roda-3.16.0/lib/roda.rb:280:in `catch'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/roda-3.16.0/lib/roda.rb:280:in `call'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/roda-3.16.0/lib/roda.rb:243:in `block in build_rack_app'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rack-2.0.6/lib/rack/common_logger.rb:33:in `call'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rack-2.0.6/lib/rack/sendfile.rb:111:in `call'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rack-2.0.6/lib/rack/method_override.rb:22:in `call'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/roda-3.16.0/lib/roda.rb:137:in `call'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/falcon-0.21.0/lib/falcon/adapters/rack.rb:173:in `call'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/async-http-0.37.12/lib/async/http/middleware.rb:57:in `call'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/falcon-0.21.0/lib/falcon/adapters/rewindable.rb:61:in `call'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/async-http-0.37.12/lib/async/http/middleware.rb:57:in `call'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/async-http-0.37.12/lib/async/http/content_encoding.rb:44:in `call'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/async-http-0.37.12/lib/async/http/middleware.rb:57:in `call'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/async-http-0.37.12/lib/async/http/server.rb:61:in `block in accept'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/async-http-0.37.12/lib/async/http/protocol/http2/server.rb:63:in `each'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/async-http-0.37.12/lib/async/http/server.rb:50:in `accept'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/async-io-1.18.2/lib/async/io/socket.rb:95:in `block in accept_each'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/async-io-1.18.2/lib/async/io/ssl_socket.rb:131:in `block in accept'
  /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/async-1.15.1/lib/async/task.rb:199:in `block in make_fiber'
13.83s: <Async::Task:0x3fd35ad54608 failed>
      |  OpenSSL::SSL::SSLError: SSL_accept returned=1 errno=0 state=unknown state: tlsv1 alert unknown ca
      |  → /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/async-io-1.18.2/lib/async/io/generic.rb:141 in `accept_nonblock'
      |    /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/async-io-1.18.2/lib/async/io/generic.rb:141 in `async_send'
      |    /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/async-io-1.18.2/lib/async/io/generic.rb:47 in `block in wrap_blocking_method'
      |    /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/async-io-1.18.2/lib/async/io/ssl_socket.rb:129 in `block in accept'
      |    /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/async-1.15.1/lib/async/task.rb:199 in `block in make_fiber'
```

**Comment by janko** [comment]
Falcon runs the server on `https://localhost:9292` by default (in order to support HTTP/2 which requires SSL), and uses a self-signed SSL certificate for that. When you a tus file is attached and promoted to Shrine permanent storage, `Shrine::Storage::Tus` attempts to download the tus file from a `https://localhost:9292/files/<uid>` URL. This fails, because the downloader doesn't have the required certificate.

Previously I always tested on `http://localhost:9292`, so I never checked whether it works on SSL. I now updated the demo app to correctly set Falcon's SSL certificate for `Shrine::Storage::Tus`, so it should be working now.

**Comment by pierreyves-lebrun** [comment]
Yes, that all works now!
Thanks for your awesome work which is going to be very helpful for my projects.

May I ask you, would you recommend using tus-server with Falcon in production or is it better to use a well tested and bulletproof app server like passenger or puma?

**Comment by janko** [comment]
It's difficult to give a straight answer, as it really depends. If you're going to mount tus-server inside your Ruby/Rails app, then it's probably better if you use battle-tested app servers like Passenger or Puma (as I've encountered some bugs with Falcon in the past). If you're going to run tus-server as a standalone app, you might want to consider using Falcon.

If you're expecting your users to have high network latency, you might not want to enable chunking for tus-js-client (so that it uploads files in one request). In this case you need to use Falcon, as it's the only app server that supports non-blocking streaming (where web workers aren't blocked waiting for data to be uploaded).

If you're ok with chunking, then it's possible to user other web servers, but there are still performance considerations. For example, Unicorn and Passenger stream request body, so you need to make sure to have Nginx in front with request/response buffering enabled (so that "slow clients" don't clog your request throughput).

Puma already has request buffering effectively built in, but web workers will still be blocked by downloads (the tus-server is considered temporary storage; you'll want to move uploaded files to permanent storage, which could mean downloading them from tus-server for re-uploading somewhere else). So you can put Nginx in front with response buffering. Alternative, if you want to avoid downloading from the tus-server app, you can have tus-server download endpoint redirect to the file on S3 if you're using it as tus-server storage. Yet another alternative is to download directly from the tus-server storage, which is possible and supported by shrine-tus gem but couples your app to the tus-server storage.

-------

I wish I could give you a simpler answer, but it's difficult to recommend once specific configuration. I this helps you decide what configuration might suit your use case best.

**Comment by pierreyves-lebrun** [comment]
Thanks for your precious advices.

My app involves a lot of file uploads so I was tempted to try Falcon out. I really like the idea of streaming rather than splitting files into many requests through chunking.

Using the same web server for both dev and prod also sounds very appealing.

Pleas keep up the good work anyway!
